[layers]
base = [
    { scan_code = 0x29, characters = "ˆ" },
    { scan_code = 0x02, characters = "1234567890-`" },
    { scan_code = 0x10, characters = "xvlcwkhgfqß´" },
    { scan_code = 0x1E, characters = "uiaeosnrtdy" },
    { scan_code = 0x2C, characters = "üöäpzbm,.j" },
    { scan_code = 0x2A, layer = "shift", forward_scan_code = true }, # left shift
    { scan_code = 0xE036, layer = "shift", forward_scan_code = true }, # right shift
    { scan_code = 0x3A, layer = "symbols" }, # caps lock
    { scan_code = 0x2B, layer = "symbols" }, # '\' on US layout, `#` key on german layout
    { scan_code = 0x56, layer = "numpad" }, # '>' on german layout
    { scan_code = 0xE038, layer = "numpad" }, # 'right alt' US layout, 'Alt Gr` on german layout
]

shift = [
    { scan_code = 0x29, characters = "ˇ" },
    { scan_code = 0x02, characters = "°§ℓ»«$€„“”—¸" },
    { scan_code = 0x10, characters = "XVLCWKHGFQẞ˜" },
    { scan_code = 0x1E, characters = "UIAEOSNRTDY" },
    { scan_code = 0x2C, characters = "ÜÖÄPZBM–•J" },
    { scan_code = 0x3A, layer = "l5" }, # caps lock
    { scan_code = 0x2B, layer = "l5" }, # '\' on US layout, `#` key on german layout
]

symbols = [
    { scan_code = 0x29, characters = "↻" },
    { scan_code = 0x02, characters = "¹²³›‹¢¥‚‘’—˚" },
    { scan_code = 0x10, characters = "…_[]^!<>=&ſ/" },
    { scan_code = 0x1E, characters = "\\/{}*?()-:@" },
    { scan_code = 0x2C, characters = "#$|~`+%\"';" },
    { scan_code = 0x2A, layer = "l5", forward_scan_code = true }, # left shift
    { scan_code = 0xE036, layer = "l5", forward_scan_code = true }, # right shift
    { scan_code = 0x56, layer = "l6" }, # '>' on german layout
    { scan_code = 0xE038, layer = "l6" }, # 'right alt' US layout, 'Alt Gr` on german layout
]

numpad = [
    { scan_code = 0x29, characters = "˙" },
    { scan_code = 0x02, characters = "ªº№⋮·£¤0/*-¨" },
    { scan_code = 0x3A, layer = "l6" }, # caps lock
    { scan_code = 0x2B, layer = "l6" }, # '\' on US layout, `#` key on german layout
]

l5 = [
    { scan_code = 0x29, characters = "˞" },
    { scan_code = 0x02, characters = "₁₂₃♂♀⚥ϰ⟨⟩₀-῾" },
    { scan_code = 0x10, characters = "ξ\u0000λχωκψγφς᾿" },
    { scan_code = 0x1E, characters = "\u0000ιαεοσνρτδυ" },
    { scan_code = 0x2C, characters = "\u0000ϵηπζβμϱϑθ" },
    { scan_code = 0x39, characters = "\u202F" }, # no-break space
]

l6 = [
    { scan_code = 0x29, characters = "." },
    { scan_code = 0x02, characters = "¬∨∧⊥∡∥→∞∝⌀╌¯" },
    { scan_code = 0x10, characters = "Ξ√ΛℂΩ⨯ΨΓΦℚ∘˘" },
    { scan_code = 0x1E, characters = "⊂∫∀∃∈Σℕℝ∂Δ∇" },
    { scan_code = 0x2C, characters = "∪∩ℵΠℤ⇐⇔⇒↦Θ" },
]
